<!DOCTYPE html>
<html lang="fr">
<head>
    <link rel="stylesheet" href="/asset/css/style.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Event</title>
    <link rel="stylesheet" href="/asset/css/style.css">
</head>
<body>
    <header>
        <nav>
            <div>
                <img class="logo" src="/asset/image/logo.png" alt="logo d'Event">
                <img class="logoRemove" src="/asset/image/logo remouv.png" alt="logo d'event">
            </div>

            <ul>
                <li>
                    <a href="<?= url('/') ?>">Home</a>
                </li>
                <li>

                    <a href="<?= url('/signUp') ?>">Sign Up</a>
                </li>
                <li>
                    <a href="<?= url('/category') ?>">Créer catégorie</a>

                </li>
            </ul>
        </nav>
    </header>

    <?php require $template . '.phtml' ?>

    
</body>
</html>