<!DOCTYPE html>
<html lang="en">
<head>
        <!-- CSS -->
    <link rel="stylesheet" href="/asset/css/style.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Event</title>

</head>
<body>
    <header>
        <nav>
            <div>
                    <img src="/asset/image/logo.png" alt="">
            </div>
            <ul>
                <li>
                    <a href="<?= url('/') ?>">Home</a>
                </li>
                <li>

                    <a href="<?= url('/signUp') ?>">Sign Up</a>
                </li>
                <li>
                    <a href="<?= url('/category') ?>">Créer catégorie</a>

                </li>
            </ul>
        </nav>
    </header>

    <main>

    <?php require $template . '.phtml' ?>
    </main>

    
</body>
</html>